name: Check Code Quality And Execute Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vue-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: keita-hino/vue-tsc-action@main